apiVersion: v1
kind: Service
metadata: { name: minio }
spec:
  selector: { app: minio }
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: 9000
    - name: console
      port: {{ .Values.service.console }}
      targetPort: 9001
