apiVersion: apps/v1
kind: StatefulSet
metadata: { name: neo4j }
spec:
  serviceName: neo4j
  replicas: 1
  selector: { matchLabels: { app: neo4j } }
  template:
    metadata: { labels: { app: neo4j } }
    spec:
      containers:
        - name: neo4j
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: NEO4J_AUTH
              value: "none"
          ports:
            - containerPort: 7687
            - containerPort: 7474
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        resources: { requests: { storage: {{ .Values.persistence.size }} } }
