apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-graph
  labels:
    app: knowledge-graph
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: knowledge-graph
  template:
    metadata:
      labels:
        app: knowledge-graph
    spec:
      containers:
        - name: knowledge-graph
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: SERVICE_NAME
              value: "knowledge-graph"
