apiVersion: v1
kind: Service
metadata: { name: rabbitmq }
spec:
  selector: { app: rabbitmq }
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: 5672
    - name: mgmt
      port: {{ .Values.service.mgmtPort }}
      targetPort: 15672
